name: Release

on: push

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codfish/semantic-release-action@v2
        with:
          dry_run: true
          plugins: |
            [
              ["@semantic-release/commit-analyzer", {
                "preset": "angular",
                "parserOpts": {
                  "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING", "RELEASE NOTE"]
                }
              }],
              ["@semantic-release/release-notes-generator", {
                "preset": "angular",
                "parserOpts": {
                  "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING", "RELEASE NOTE"]
                },
                "writerOpts": {
                  "commitsSort": ["subject", "scope"]
                }
              }]
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
